### ISSUE TITLE
Usage doc and issue with no .scummvm files

### ISSUE THREAD

**Issue by espenaf** [i30817/libretro-mkscumm#1]
I have read the README and some of the comments in the code, but I can`t get the tool to work for me. Might be that I doing something wrong, so the process i am using is:

1. Start Retroarch, add ScummVM engine
2. Mass scan via Import Content -> Scan Directory -> Select folder with ScummVM games
3. Verify under ScummVM that the games where added, and remove any false positives
4. Run libretro-mkscumm from commandline
5. Verify that each game has a new .scummvm file

After running the libretro-mkscumm I see no change in the game directories, but the .config/retroarch/playlists/ScummVM.lpl file has been reset to just

```
{
    "version": "1.5",
    "default_core_path": "/usr/lib/libretro/scummvm_libretro.so",
    "default_core_name": "ScummVM",
    "base_content_directory": "",
    "label_display_mode": 0,
    "right_thumbnail_mode": 0,
    "left_thumbnail_mode": 0,
    "sort_mode": 0,
    "scan_content_dir": "",
    "scan_file_exts": "scummvm",
    "scan_dat_file_path": "",
    "scan_search_recursively": false,
    "scan_search_archives": false,
    "scan_filter_dat_content": false,
    "items": []
}
```

The same file before running was

```
{
  "version": "1.5",
  "default_core_path": "/usr/lib/libretro/scummvm_libretro.so",
  "default_core_name": "ScummVM",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "sort_mode": 0,
  "items": [
    {
      "path": "/home/user/scummvm/Conquests of the Longbow: The Adventures of Robin Hood (DOS)/ADLIB.BIN",
      "entry_slot": -1612285696,
      "label": "Adventures of Robin Hood, The",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "210ACDE5|crc",
      "db_name": "ScummVM.lpl"
    },
    { 
      "path": "/home/user/scummvm/Conquests of Camelot - The Search for the Grail/RESOURCE.001",
      "entry_slot": -1612285696,
      "label": "Conquests of Camelot: King Arthur, Quest for the Grail",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "6DBC7908|crc",
      "db_name": "ScummVM.lpl"
    },
    { 
      "path": "/home/user/scummvm/Castle of Dr. Brain/RESOURCE.000",
      "entry_slot": -1612285696,
      "label": "Castle of Dr. Brain",
      "core_path": "DETECT",
      "core_name": "DETECT",
      "crc32": "E2CA0E91|crc",
      "db_name": "ScummVM.lpl"
    }
  ]
}
```

**Comment by i30817** [comment]
You're doing '2' wrong. The idea is to mass add from inside the the scummvm core, that is 'start core' from retroarch, mass add your games, and _then_ run the application.

Mass adding from 'inside the core' creates the the scummvm.ini file which is essential for the core to work correctly. The second part of 'working correctly' is that the signatures from inside that file (the things between [] ) are the text inside the .scummvm files, but the application handles that.

I should clarify that in the readme more though.

**Comment by i30817** [comment]
The reason why it is essential btw is that the scummvm core sometimes adds a bunch of engine parameters when you add a game. Those parameters are needed. Sometimes they're things about language, sometimes they're things about game variants, sometimes the engine will add a _variant that doesn't normally exist_.

For instance the games blade runner, ultima 4 and ultima 6 add a 'enhanced version' besides the normal one if you scan them from inside scummvm, because scummvm has game patches for them that turn the games into 'enhanced versions' and the devs decided doing it that way instead of anything else.

**Comment by espenaf** [comment]
Thanks for the clarification. I think some of the issue for me was that the Mass Add button is hidden behind holding down the shift. I have been using ScummVM now and again, but this functionality was unknown to me, therefore I just assumed it was the Retroarch Content Import.

**Comment by i30817** [comment]
I updated the documentation and added a functionality to check for the existence of the retroarch 'system/scummvm/extra' folder which usually contains the updated scummvm engine files. Then it adds the 'extrapath' ini entry to the scummvm.ini file so you don't need to add it in the options of the core too.

I'll edit it again to say that the 'mass add button' is under the arrow on the GUI.

A warning: the core system files in scummvm/extra, if you're using the diablodiab core daily build version need to be the upstream master files, because scummvm changes them often.

**Comment by i30817** [comment]
Also it sets the save path to the retroarch system/save now.

This is needed because autosave was breaking the core, because it couldn't find the location to save to.

**Comment by i30817** [comment]
@espenaf , if you're using the diablodiab core, the documentation/readme now has a link to the right scummvm engine data files.

Turns out recommending 'upstream' files for that core was a mistake, since the buildbot is not tracking upstream for 'every commit', just once in a while, so it's easy to get things out of sync doing that. Using the new zip that the buildbot provides assures they're not out of sync and that games load (except grim fandango and escape from monkey island because diablodiab forgot to include/build the data files for those games into the zip, though i suppose it's only a question of time)

**Comment by espenaf** [comment]
Was not using diablodiab, but it looks interesting. Will look more into that, and the updated doc. Thanks for all the great work.
