### ISSUE TITLE
Invalid Retroarch playlist directory

### ISSUE THREAD

**Issue by CoCoDaggorath** [i30817/libretro-mkscumm#2]
No matter what parameters I use for --playlist, I get the following error:

Invalid Retroarch playlist directory: :\playlists

I'm running:
   - Windows 11
   - Python 3.11.1. (which includes pip)
   - libretro_scummvm_playlist-2.2.5-py3-none-any.whl
   - RetroArch 1.14.0 (x64)

I installed RetroArch to the default directory: RetroArch-Win64.  retroarch.cfg is located in that same directory. I've tried  the following:

libretro-scummvm-playlist C:\RetroArch-Win64\retroarch.cfg --playlist C:\RetroArch-Win64\playlists\ScummVM.lpl
libretro-scummvm-playlist C:\RetroArch-Win64\retroarch.cfg --playlist ScummVM.lpl
libretro-scummvm-playlist C:\RetroArch-Win64\retroarch.cfg

I get the following error every single time: Invalid Retroarch playlist directory: :\playlists

I've followed all the steps. I ran the ScummVM core and scanned several of the scummvm games so that RetroArch created the C:\RetroArch-Win64\\system\scummvm.ini file.

Any help would be appreciated. Thanks!

**Comment by i30817** [comment]
What's happening is probably your retroarch playlist directory inside the retroarch.cfg is badly configured.

There is a test in the program that triggers if that line 'value' is not a directory in the filesystem or is not writable (because the directory needs to be writable to write or rewrite playlists).

Open the file in a text editor and show me (or fix it yourself) the 'playlist_directory' entry.


The error message could be better i guess.

It's still possible it's a bug in my program failing at reading a 'valid' retroarch playlist entry directory [here](https://github.com/i30817/libretro-mkscumm/blob/0e04a864773dd1ca783ca799799d2055e3825efd/libretro_scummvm_playlist/__main__.py#L64) but i find that unlikely to have a error like ':\playlists' is not the fault of my program since it does no transformation except remove quotes around the value. 

If the value is ':\playlists' retroarch itself is _very_ confused about
1. your drive
2. the home directory of the program
 
I recommend checking the paths in retroarch settings->directory entries to check if they all exist and are right.

**Comment by i30817** [comment]
Could also be that there is some special form of special path for 'under the main directory' i guess that uses that form. Not sure if that exists. Never heard of it frankly.

Do the playlists you already have for other cores actually work (show) in retroarch?

**Comment by i30817** [comment]
Turns out there was a special form of 'default path' in cfg files but it was a different name than you showed (it's 'default' in the cfg file).

I made a new release that

1. points to the cfg files lines when these paths errors occur
2. when the value is 'default' i use the cfg directory as a parent dir and the default name of the directory to try to get it, playlists for playlist_directory, cores for libretro_directory etc.

Your problem is still a corrupt retroarch.cfg though and i can't do anything to prevent that. Still, do post what was in the 'playlist_directory' line in your retroarch.cfg just to make sure.

**Comment by CoCoDaggorath** [comment]
Thanks for your quick response! Wow - I'm really blown away!

I checked my retroarch.cfg.  All of the default locations all started with ":\".  So the defaults all look like this:
content_database_path = ":\database\rdb"
core_assets_directory = ":\downloads"
cursor_directory = ":\database\cursors"
dynamic_wallpapers_directory = ":\assets\wallpapers"
playlist_directory = ":\playlists"
etc, etc, etc

I did not change any of these from the defaults. Every time RA is ran, it resets the paths back to these defaults that start with ":\".

This must be a RA issue with Windows, because look at my Android retroarch.cfg, they all have fully populated pathnames. (e.g. overlay_directory = "/data/user/0/com.retroarch.aarch64/overlays").

Running the updated code (2.2.26) with the default paths, I get the following:

Invalid retroarch.cfg line: playlist_directory=":\playlists"

I then did a search-and-replace:
   Find:   ":\
   Replace With:  "C:\RetroArch-Win64\

Then, after re-running, it worked perfectly and all the .scummvm files are created in each directory! (THANK GOODNESS!)  However, it should be noted that running RA again resets each and every one of the paths back to the default starting with the ":\".  It probably doesn't matter at this point though since the .scummvm files are all created.

**Comment by i30817** [comment]
You should report this bug in the retroarch bug reporter, saying the version of the program you're using, where you got it and the environment. Keep your config file and drag and drop it into the bug report form too.

Retroarch shouldn't behave like this. You would get 'strange' problems running games on it if it can't find paths, like not being able to save or savestate.

Scummvm even crashes if it can't find a place to save (scummvm autosaves by default); which is why this program reads the retroarch 'save' directory location, to be able to set it in the scummvm.ini.

**Comment by i30817** [comment]
Actually, i'm communicating with the RA devs and it appears this is a behavior that actually exists and not a bug like i thought. But it's apparently windows only for some reason. I'll 'fix' it.

**Comment by i30817** [comment]
I think this will fix it without the need to change paths. I recommend redoing a run because it's not _just_ the playlist directory the program needs, some paths are rewritten into the scummvm.ini file too.

Specifically it writes to  'extrapath', 'themepath', 'savepath' and 'soundfont' and the core will crash when saving if there is no savepath.

You can, naturally, set up these paths yourself by starting the core without a game on and editing the settings, or opening scummvm.ini yourself, but the program will do that for you.

**Comment by CoCoDaggorath** [comment]
Thanks for the fix! I really admire your pride of ownership to fix this issue!  The scummvm.ini isn't a problem for me, because I was actually using this in Windows to create the .scummvm files for each directory and then copying those to my Android device and then doing a search-and-replace to update the path to the games.  Your work saved me a TON of time and saved me the hassle to have to create all of those individually!

**Comment by i30817** [comment]
It could be better if i had some way to invoke a automatic creation of the scummvm.ini (maybe from the command line and the core). Although, the scummvm scanner isn't the best.

I think that this program might eventually be obsoleted because there are finally people trying to make a scummvm core that doesn't suck (from outside the retroarch project and being grandfathered in). Part of that would be integrating the scummvm scanner into the retroarch scanner imo.
