### ISSUE TITLE
*.scummvm method on Miyoo Mini Plus - cant change language

### ISSUE THREAD

**Issue by Benman2785** [i30817/libretro-mkscumm#3]
Hi,

i use Miyoo Mini Plus with OnionOS and ScummVM 2.7.0git

i also use the game.scummvm method - yet i need to speficy language of a game 

BASS has english, german and french - yet with scummvm method i can only start the game in english

would love to be able to start the game in german

**Comment by Benman2785** [comment]
or it would also be nice to make a launcher.scummvm that simply opens ScummVM Launcher :)

**Comment by i30817** [comment]
As i mentioned in the readme and the other issues you opened about this, this program only does one thing: it reads the scummvm.ini file the core is using and uses those paths (that need to be filled in by the scummvm scanner) to place .scummvm files in the right directories and create a playlist for you. 

The language is reflected on the .scummvm file because the id will be different and the 'description' (what the program picks up) will be different too. IF the scummvm scanner  doesn't bother to do 'ids' for the sky engine and the several languages it supports (I find this hard to believe because it would be a scummvm bug), it can be worked around by creating a copy paste of the 'sky' id in the the scummvm.ini playlist and changing/adding the language field like some other games have and also changing the 'description' (it's what this program uses to figure out the rest of the name for '.scummvm' files, and if it was equal, this program would clobber one of the .scummvm files when it attempted to create them.

It's the scanner that creates all the game variants, if your game has them of course. It's not unusual, i can get multiple languages in the games i have after using 'mass add' from the core gui and running this program.


You can simply open the scummvm GUI by 'loading' and starting the scummvm core.

or indeed by creating a shortcut yourself that uses `retroarch -L scummvm`.

**Comment by i30817** [comment]
Also note that it's in your best interest to use the scummvm scanner to scan the games anyway, because it will often fill in variables you couldn't possibly know about and are important to the games good functioning, in many, if not most cases.

And sometimes they will also create alternate 'game ids' that enable extra functions, like the the bladerunner/worlds of ultima will also create ids for 'enhanced versions' if you scan them in scummvm. Granted, the 'mass scanner' function in particular has a few bugs with false positives games scanned (Origin games particularly, but not only). But it's much much saner than filling in hundreds of scummvm files by hand while still not having all the data for the games to function (if you don't use the scummvm scanner).

The readme on the retroarch manual about scummvm is totally misleading about this, Filling the .scummvm files by hand with random 'engine' ids, is not only idiotic because it's so slow, it isn't even going to make for good results without matching the 'id' inside the file to a real entry on the scummvm.ini file the core is using.

**Comment by Benman2785** [comment]
ah ok:

1. i run ScummVM and add each game - so they have a ID in scummvm.ini
2. i match ID in game.scummvm with ID of scummvm.ini (like BASS id is "sky-1")
3. i still use Miyoo with Onion OS and ScummVM with miyoogamelist.xml and run the game via the .scummvm file

or did i missinterpret what was said? sry for my low knowledge and lack of time learning (as i have 2 hard weeks behind me and the next 10 days also packed)

thank you for your help so far

**Comment by i30817** [comment]
Yes, literally that. But this (libretro-scumm-playlist) program takes care of 2 (creating the files on the games directory) and creates a retroarch playlist for you. This program one and only use is to create those files and retroarch (the program) playlists.

I have no idea what 3 means because i don't have that device. Not speculating if that xml file is program created from retroarch playlists or anything else since i simply don't know.

But if it means that that launcher needs a single file to launch the games to the core, it will _probably_ also work because libretro-scumm-playlist created the scummvm files in the games directory with the right scummvm.ini IDs inside, so if the core behaves the same when being fed a .scummvm file it will work.

**Comment by Benman2785** [comment]
thank you - it works :)

scummvm.ini looks like this:

`[scumm]`
`*** (all the settings)`
` `
`[sky]`
`platform=pc`
`gameid=sky`
`alt_intro=true`
`description=Beneath a Steel Sky (v0.0372 cd)`
`language=de`
`extra=v0.0372 cd`
`path=/mnt/SDCARD/Roms/SCUMMVM/Beneath a Steel Sky (G)`
`engineid=sky`

sky.scummvm looks like this
`sky`

miyoogamelist.xml looks like this
`<?xml version="1.0"?>`
` `
`<gameList>`
`	<game>`
`		<path>./Beneath a Steel Sky (G)/sky.scummvm</path>`
`		<name>Beneath a Steel Sky (G)(PC-Speaker)</name>`
`		<image></image>`
`	</game>`
`</gamelist>`

**Comment by i30817** [comment]
Alright then.
